-- CreateTable
CREATE TABLE `Referral` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `referrerName` VARCHAR(191) NOT NULL,
    `referrerEmail` VARCHAR(191) NOT NULL,
    `referrerEmployeeId` VARCHAR(191) NULL,
    `candidateName` VARCHAR(191) NOT NULL,
    `candidateEmail` VARCHAR(191) NOT NULL,
    `candidatePhone` VARCHAR(10) NOT NULL,
    `candidateLinkedIn` VARCHAR(191) NULL,
    `candidateResumeUrl` VARCHAR(191) NOT NULL,
    `experienceLevel` VARCHAR(191) NOT NULL DEFAULT 'fresher',
    `currentJobTitle` VARCHAR(191) NOT NULL,
    `appliedJobRole` ENUM('FRONTEND_DEVELOPER', 'BACKEND_DEVELOPER', 'FULL_STACK_DEVELOPER', 'SOFTWARE_DEVELOPER', 'DATA_ANALYST', 'DATA_SCIENTIST', 'MACHINE_LEARNING_ENGINEER', 'ARTIFICIAL_INTELLIGENCE_ENGINEER', 'DEVOPS_ENGINEER', 'CLOUD_ENGINEER', 'CYBER_SECURITY_ANALYST', 'MOBILE_APP_DEVELOPER', 'GAME_DEVELOPER', 'EMBEDDED_SYSTEMS_ENGINEER', 'DATABASE_ADMINISTRATOR', 'BLOCKCHAIN_DEVELOPER', 'UI_UX_DESIGNER', 'PRODUCT_MANAGER') NOT NULL,
    `referrerNote` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
